// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace net.opgenorth.yegbuildings.m4a
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int balloon_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int balloon_overlay_bg_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int balloon_overlay_close = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int balloon_overlay_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int balloon_overlay_unfocused = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int building_medium = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int balloon_close = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int balloon_disclosure = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int balloon_inner_layout = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int balloon_item_snippet = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int balloon_item_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int balloon_main_layout = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int building_list_fragment = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int map_fragment = 2130968583;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int balloon_overlay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_description = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int buildinginfoviewer_title = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int buildinglist_row_constructiondate_label = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int buildinglist_tabtext = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int buildinglist_title = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int buildingmap_tabtext = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int buildingmap_title = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int buildingmap_unknown_location = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int google_maps_api_key = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int main_menu_my_location = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int main_menu_refreshdata = 2131034115;
			
			private String()
			{
			}
		}
	}
}
