//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.opgenorth.yegbuildings.m4a
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_description = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int buildinginfoviewer_title = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int buildinglist_row_constructiondate_label = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int buildinglist_tabtext = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int buildinglist_title = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int buildingmap_tabtext = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int buildingmap_title = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int buildingmap_unknown_location = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int main_menu_my_location = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int main_menu_refreshdata = 2130968578;
			
			private String()
			{
			}
		}
	}
}
