//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Opgenorth.Yeg.Buildings
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int header = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int main_tab_background = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int roweven = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int rowodd = 2130968578;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int building_medium = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int empty = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_mapmode = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_refresh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_list = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_list_bullets = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_map = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_map_grey = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_map_white = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int maps1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int maps2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int marker = 2130837516;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int building_distance_to_me = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int building_row_address = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int building_row_name = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int building_row_year_built = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int buildinglist_building_count = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int buildinglist_my_gps = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int main_menu_refreshdata = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int map_menu_showMyLocation = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int mapofallbuildings = 2131165190;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int buildinglist = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int historicalbuildingrow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int mapofallbuildings_debug = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int mapofallbuildings_production = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int main = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int map = 2131099649;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_description = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int buildinglist_row_constructiondate_label = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int buildinglist_tabtext = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int buildinglist_title = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int buildingmap_tabtext = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int buildingmap_title = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int buildingmap_unknown_location = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int main_menu_my_location = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int main_menu_refreshdata = 2131034114;
			
			private String()
			{
			}
		}
	}
}
